bot.token: '5402767430:AAEXVe8s8IAow9z9Ip69NCU9JnUaEHIgcrw'

messages:
  startMessage: "Hello"
  listScalesEmptyMessage: "Empty"
  listScalesMessage: "Scales:"
  errorMessage: "Error ocurred:"
  menuBackMessage: "Back"

commands:
  startCommand: "start"
  helpCommand: "help"
  listScalesCommand: "list_scales"
  createScaleCommand: "create_scales"
  textCommand: "text"
  navCommand: "nav"
