messages:
  start: "Hello and welcome to ALEC Bot (Analytical Load-Emotion-Correlation)"
  listScalesEmpty: "No scales available at the moment"
  listScales: "Scales:\n\n{scales}"

  createdScale : "A scale successfully created with id {id}"
  rejectScale: "The given scale format is invalid."
  rejectScaleProperty: "The given scale {prop} format is invalid."
  scaleNamePrompt: "Input a name of the new scale..."
  scaleUnitPrompt: "Input a unit of the new scale..."
  scaleDivisionsPrompt: "Input list of divisions for the new scale..."

  scaleIdPrompt: "Input the scale id you want to delete."
  deletedScale: "The scale was marked as deleted."
  scaleDoesNotExist: "Scale does not exist for id {id}"
  scaleAlreadyExists: "Scale already exists: {id}"

  warnAboutPurging: "WARNING: If you purge the scale, it will be no longer possible to recover it."
  purgedScale: "The scale was permanently deleted!"
  scaleIsNotMarkedAsDeleted: "Scale {id} must first be marked as DELETED before complete removal!"

  updatedNameScale : "Scale name was successfully updated"
  updatedUnitScale : "Scale unit was successfully updated"
  updatedDivisionsScale : "Scale divisions were successfully updated"

  error: "Unexpected error occurred:\n{name}:{message}"
  menuBack: "Back"

commands:
  startCommand: "start"
  helpCommand: "help"
  listScalesCommand: "list_scales"
  createScaleCommand: "create_scale"
  deleteScaleCommand: "delete_scale"
  purgeScaleCommand: "purge_scale"
  updateNameScaleCommand : "update_scale_name"
  updateUnitScaleCommand : "update_scale_unit"
  updateDivisionsScaleCommand : "update_scale_div"
  textCommand: "text"
  navCommand: "nav"

runner:
  bot:
    token: '5402767430:AAEXVe8s8IAow9z9Ip69NCU9JnUaEHIgcrw'
  active: bot