messages:
  start: "Hello and welcome to ALEC Bot (Analytical Load-Emotion-Correlation)"
  listScalesEmpty: "No scales available at the moment"
  listScales: "Scales:\n\n{scales}"

  createdScale : "A scale successfully created with id {id}"
  rejectScale: "The given scale format is invalid."
  rejectScaleProperty: "The given scale {prop} format is invalid."
  scaleNamePrompt: "Input a name of the new scale..."
  scaleUnitPrompt: "Input a unit of the new scale..."
  scaleDivisionsPrompt: "Input list of divisions for the new scale..."

  scaleIdPrompt: "Input the scale id you want to delete"
  deletedScale: "The scale was marked as deleted"
  scaleDoesNotExist: "Scale does not exist for id {id}"

  error: "Unexpected error occurred:\n{name}:{message}"
  menuBack: "Back"

commands:
  startCommand: "start"
  helpCommand: "help"
  listScalesCommand: "list_scales"
  createScaleCommand: "create_scale"
  deleteScaleCommand: "delete_scale"
  purgeScaleCommand: "purge_scale"
  updateScaleCommand: "update_scale"
  textCommand: "text"
  navCommand: "nav"

runner:
  bot:
    token: '5402767430:AAEXVe8s8IAow9z9Ip69NCU9JnUaEHIgcrw'
  active: bot