messages:
  startMessage: "Hello and welcome to ALEC Bot (Analytical Load-Emotion-Correlation)"
  listScalesEmptyMessage: "No scales available at the moment"
  listScalesMessage: "Scales:\n\n{scales}"

  rejectScaleMessage: "Scale format is invalid."
  rejectScalePropertyMessage: "Scale {prop} format is invalid."
  scaleNamePrompt: "Input a name of the new scale."
  scaleUnitPrompt: "Input a unit of the new scale."
  scaleDivisionsPrompt: "Input list of divisions for the new scale."

  createdScaleMessage : "A scale successfully created with id {id}"

  errorMessage: "Unexpected error occurred:\n{name}:{message}"
  menuBackMessage: "Back"

commands:
  startCommand: "start"
  helpCommand: "help"
  listScalesCommand: "list_scales"
  createScaleCommand: "create_scales"
  textCommand: "text"
  navCommand: "nav"

runner:
  bot:
    token: '5402767430:AAEXVe8s8IAow9z9Ip69NCU9JnUaEHIgcrw'
  active: bot