messages:
  startMessage: "Hello"
  listScalesEmptyMessage: "No scales available at the moment"
  listScalesMessage: "Scales:\n\n%s"

  rejectScaleMessage: "Scale is invalid"
  rejectScaleNameMessage: "Scale name is invalid"
  rejectScaleUnitMessage: "Unit is invalid"
  rejectScaleDivisionsMessage: "Scale division is invalid"
  scaleNamePrompt: "Input name"
  scaleUnitPrompt: "Input unit"
  scaleDivisionsPrompt: "Input divisions"

  errorMessage: "Error ocurred:"
  menuBackMessage: "Back"

commands:
  startCommand: "start"
  helpCommand: "help"
  listScalesCommand: "list_scales"
  createScaleCommand: "create_scales"
  textCommand: "text"
  navCommand: "nav"

runner:
  bot:
    token: '5402767430:AAEXVe8s8IAow9z9Ip69NCU9JnUaEHIgcrw'
  active: bot